Repository LetsEatCo/Restaurants, pull requests merged in 2018-11, with the labels that each got.

#60 refactor: Reformat project according to ESLint style rule
  .eslintrc
  src/components/Dashboard/AddKioskForm.vue
  src/components/Dashboard/LoginForm.vue
  src/components/Dashboard/Meal/AddMealForm.vue
  src/components/Dashboard/Meal/EditMealForm.vue
  src/components/Dashboard/Product/AddProductForm.vue
  src/components/Dashboard/Product/EditProductForm.vue
  src/components/Dashboard/Stock/AddIngredientForm.vue
  src/components/Dashboard/Stock/EditIngredientForm.vue
  src/components/Dashboard/StoreProfile.vue
  src/components/Dashboard/StoreProfileEditForm.vue
  src/components/Home/RegisterForm.vue
  src/layouts/Dashboard/DashboardLayout.vue
  src/layouts/Dashboard/components/Sidebar/SidebarItem.vue
  src/layouts/Dashboard/components/Sidebar/index.vue
  src/layouts/HomepageLayout.vue
  src/middleware/login-redirect.js
  src/pages/dashboard/index.vue
  src/pages/dashboard/kiosks/add/index.vue
  src/pages/dashboard/meals/_uuid.vue
  src/pages/dashboard/meals/index.vue
  src/pages/dashboard/products/index.vue
  src/pages/dashboard/profile/edit/index.vue
  src/pages/dashboard/profile/index.vue
  src/pages/dashboard/stock/index.vue
  src/pages/index.vue
  src/pages/login.vue
  src/store/index.js
  src/store/modules/store/store.kiosks.module.js
  src/store/modules/store/store.module.js
Labels: status: done 🙌, type: enhancement 🐺

#68 feat: Update Section
  src/components/Dashboard/Sections/AddSectionForm.vue
  src/components/Dashboard/Sections/EditSectionForm.vue
  src/layouts/Dashboard/menu.js
  src/pages/dashboard/sections/index.vue
  src/store/actions/store/store.sections.actions.js
  src/store/index.js
  src/store/modules/store/index.js
  src/store/modules/store/store.products.module.js
  src/store/modules/store/store.sections.module.js
Labels: priority: high 🔥, scope: back-office, scope: functional, status: done 🙌, type: feature ✨

#66 feat: Create Sections
  src/components/Dashboard/Meal/EditMealForm.vue
  src/pages/dashboard/sections/index.vue
  src/store/modules/store/store.sections.module.js
Labels: priority: medium 🚧, scope: back-office, scope: functional, status: done 🙌, type: feature ✨

#69 feat: Add Products / Meals to Section
  src/components/Dashboard/Sections/AddSectionProductForm.vue
  src/pages/dashboard/sections/index.vue
  src/store/actions/store/store.sections.actions.js
  src/store/modules/store/store.sections.module.js
Labels: priority: high 🔥, scope: back-office, scope: design, scope: functional, status: done 🙌, type: feature ✨

#70 feat: Add view Section
  src/pages/dashboard/sections/_uuid.vue
  src/pages/dashboard/sections/index.vue
  src/store/actions/store/store.sections.actions.js
  src/store/modules/store/store.sections.module.js
Labels: priority: high 🔥, scope: back-office, scope: design, scope: functional, status: done 🙌, type: feature ✨
