Repository LetsEatCo/Restaurants, pull requests merged in 2018-10, with the labels that each got.

#9 ✨ feat: Add login form
  nuxt.config.js
  package.json
  src/components/Dashboard/LoginForm.vue
  src/middleware/login-redirect.js
  src/pages/dashboard/login.vue
  src/pages/index.vue
  src/plugins/local-storage.js
  src/store/actions/auth.actions.js
  src/store/actions/store.actions.js
  src/store/index.js
  src/store/modules/auth.module.js
  src/store/modules/store.module.js
  yarn.lock
Labels: priority: high 🔥, scope: authentication, scope: front, scope: functional, status: done 🙌, type: feature ✨

#10 chore(security): 🍪 Secure authentication with cookies
  nuxt.config.js
  package.json
  src/middleware/login-redirect.js
  src/plugins/cookies-state.js
  src/store/index.js
  src/store/modules/auth.module.js
  yarn.lock
Labels: priority: medium 🚧, scope: authentication, scope: functional, status: done 🙌, type: enhancement 🐺

#11 ✨ feat: Add registration form
  nuxt.config.js
  src/components/Home/RegisterForm.vue
  src/pages/index.vue
  src/plugins/cookies-state.js
  src/store/actions/register.actions.js
  src/store/index.js
  src/store/modules/auth.module.js
  src/store/modules/register.module.js
  src/store/modules/store.module.js
Labels: priority: medium 🚧, scope: authentication, scope: front, scope: functional, status: done 🙌, type: feature ✨

#12 ✨ feat: Add create Kiosk form
  src/components/Dashboard/AddKioskForm.vue
  src/middleware/login-redirect.js
  src/pages/dashboard/kiosks/add/index.vue
  src/pages/dashboard/login.vue
  src/plugins/local-storage.js
  src/store/actions/store/store.actions.js
  src/store/actions/store/store.kiosks.actions.js
  src/store/index.js
  src/store/modules/auth.module.js
  src/store/modules/register.module.js
  src/store/modules/store/index.js
  src/store/modules/store/store.kiosks.module.js
  src/store/modules/store/store.module.js
Labels: priority: medium 🚧, scope: back-office, scope: functional, status: done 🙌, type: feature ✨

#14 chore(design): Structure Backoffice
  nuxt.config.js
  package.json
  src/layouts/Dashboard/DashboardLayout.vue
  src/layouts/Dashboard/components/Sidebar/SidebarItem.vue
  src/layouts/Dashboard/components/Sidebar/index.vue
  src/layouts/Dashboard/components/index.js
  src/layouts/Dashboard/menu.js
  src/pages/dashboard/index.vue
  src/pages/dashboard/kiosks/add/index.vue
  src/utils/index.js
  yarn.lock
Labels: priority: medium 🚧, scope: back-office, scope: design, status: done 🙌, type: enhancement 🐺

#17 enhance: Store Address
  src/components/Dashboard/StoreProfile.vue
  src/components/Dashboard/StoreProfileEditForm.vue
  src/components/Home/RegisterForm.vue
  src/layouts/Dashboard/DashboardLayout.vue
  src/layouts/Dashboard/menu.js
  src/pages/dashboard/index.vue
  src/pages/dashboard/profile.vue
  src/pages/dashboard/profile/edit/index.vue
  src/pages/dashboard/profile/index.vue
Labels: priority: medium 🚧, scope: back-office, scope: front, scope: functional, status: done 🙌, type: enhancement 🐺

#18 design: Home and Login pages design
  nuxt.config.js
  package.json
  src/components/Dashboard/LoginForm.vue
  src/components/Home/RegisterForm.vue
  src/layouts/HomepageLayout.vue
  src/middleware/login-redirect.js
  src/pages/dashboard/login.vue
  src/pages/index.vue
  src/pages/login.vue
  src/plugins/local-storage-persisted-state.js
  src/plugins/mq.js
  src/store/index.js
  src/store/modules/auth.module.js
  src/store/modules/store/store.kiosks.module.js
  src/store/modules/store/store.module.js
  yarn.lock
Labels: priority: medium 🚧, scope: design, scope: front, scope: functional, status: done 🙌, type: enhancement 🐺

#25 feat + design: Add Ingredient create Form
  nuxt.config.js
  src/middleware/login-redirect.js
  src/pages/dashboard/ingredients/index.vue
  src/plugins/auth.js
  src/store/index.js
  src/store/modules/store/store.ingredients.module.js
  src/store/modules/store/store.module.js
Labels: priority: high 🔥, scope: back-office, scope: design, scope: functional, status: done 🙌, type: feature ✨

#26 feat + design: Add delete ingredients
  src/pages/dashboard/ingredients/index.vue
  src/store/actions/store/store.ingredients.actions.js
  src/store/modules/store/store.ingredients.module.js
Labels: priority: medium 🚧, scope: back-office, scope: design, scope: functional, status: done 🙌, type: feature ✨

#27 feat+design: Add update Ingredients
  package.json
  src/pages/dashboard/ingredients/index.vue
  src/store/actions/store/store.ingredients.actions.js
  src/store/modules/store/store.ingredients.module.js
  src/utils/index.js
Labels: priority: medium 🚧, scope: back-office, scope: design, scope: functional, status: done 🙌, type: feature ✨

#33 feat: Add Products list View
  config/default.js
  nuxt.config.js
  package.json
  src/components/Dashboard/Stock/AddIngredientForm.vue
  src/components/Dashboard/Stock/EditIngredientForm.vue
  src/layouts/Dashboard/DashboardLayout.vue
  src/layouts/Dashboard/menu.js
  src/pages/dashboard/ingredients/index.vue
  src/pages/dashboard/products/index.vue
  src/pages/dashboard/stock/index.vue
  src/store/actions/store/store.products.actions.js
  src/store/index.js
  src/store/modules/auth.module.js
  src/store/modules/register.module.js
  src/store/modules/store/index.js
  src/store/modules/store/store.ingredients.module.js
  src/store/modules/store/store.kiosks.module.js
  src/store/modules/store/store.module.js
  src/store/modules/store/store.products.module.js
  src/utils/event-bus.js
  yarn.lock
Labels: priority: high 🔥, scope: back-office, scope: design, scope: functional, status: done 🙌, type: feature ✨

#34 feat: Add Product Form
  src/components/Dashboard/Product/AddProductForm.vue
  src/layouts/Dashboard/DashboardLayout.vue
  src/layouts/Dashboard/components/Sidebar/index.vue
  src/pages/dashboard/products/index.vue
  src/store/modules/store/store.ingredients.module.js
  src/utils/quantity-range.js
Labels: priority: high 🔥, scope: back-office, scope: design, scope: functional, status: done 🙌, type: feature ✨

#35 feat: ✨ delete product
  src/pages/dashboard/products/index.vue
Labels: priority: medium 🚧, scope: back-office, scope: functional, status: done 🙌, type: feature ✨

#41 feat: View Meals
  src/layouts/Dashboard/DashboardLayout.vue
  src/layouts/Dashboard/menu.js
  src/pages/dashboard/meals/_uuid.vue
  src/pages/dashboard/meals/index.vue
  src/pages/dashboard/stock/index.vue
  src/store/actions/store/store.meals.actions.js
  src/store/index.js
  src/store/modules/store/index.js
  src/store/modules/store/store.meals.module.js
Labels: priority: high 🔥, scope: back-office, scope: design, scope: functional, status: done 🙌, type: feature ✨

#42 feat: Create Meals
  src/components/Dashboard/Meal/AddMealForm.vue
  src/components/Dashboard/Product/AddProductForm.vue
  src/layouts/Dashboard/DashboardLayout.vue
  src/pages/dashboard/meals/index.vue
  src/store/modules/store/store.products.module.js
  src/utils/quantity-range.js
Labels: priority: medium 🚧, scope: back-office, scope: design, scope: functional, status: done 🙌, type: feature ✨
